# Generated by Django 4.2.9 on 2024-01-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goods',
            name='date_of_addition',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
